name: android-build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: set up lua
      uses: xpol/setup-lua@v0.2
      with:
        lua-version: "5.3.5"

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure Toolset
      shell: bash
      working-directory: build
      run: cmake $GITHUB_WORKSPACE/frameworks/toolset -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DLUA=lua54

    - name: Build Toolset
      working-directory: build
      shell: bash
      run: cmake --build .

    - name: Install Toolset
      working-directory: build
      shell: bash
      run: cmake --install .

    - name: Build with Gradle
      run: cd runtime-src/proj.android && ./gradlew assembleRelease
